### ISSUE TITLE
worng pod parsing

### ISSUE THREAD

**Issue by KES777** [jmcnamara/pod-simple-wiki#6]
parsing pod like:

 # numbered list line 1
 # numbered list line 2
 # numbered list line 3

produce text in wiki:
1. numbered list line 1 # numbered list line 2 # numbered list line 3

expected:
1. numbered list line 1
2. numbered list line 2
3. numbered list line 3

**Comment by zoffixznet** [comment]
I believe what the OP is refererring to is that this sample pod:

```
=pod

=over 5

=item First Item

=item Second Item

=item Another Item

=back
```
Translates to a single-item list in some wikis (e.g. Confluence) and or what what looks like plain text to me (in wiki format).

The reason for the bug is that in this case `Pod::Simple` outputs a `<dl>` full of `<dt>`s only. It's a reported, stalled bug on RT: https://rt.cpan.org/Ticket/Display.html?id=59555

In summation, this issue should be closed and the bug addressed in `Pod::Simple` instead. Once it's resolved there, the issue in `Pod-Simple-Wiki` will be resolved as well.

**Comment by jmcnamara** [comment]
> In summation, this issue should be closed and the bug addressed in Pod::Simple instead. Once it's resolved there, the issue in Pod-Simple-Wiki will be resolved as well.

Okay. Closing.
